import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head />
			<body className='flex flex-col min-h-screen'>
				<Providers themeProps={{ attribute: "class", defaultTheme: "light" }}>
						<main className="relative overflow-hidden flex-1 min-h-screen" style={{ background: "white"}}>
							{/* <ToastContainer /> */}
							{children}
						</main>
            		{/* <Footer /> */}
				</Providers>
			</body>
		</html>
	);
}
